hello-world:
  image: java:openjdk-8u91
  hostname: "openjdk7.mageddo"
  volumes:
    - $PWD/build:/opt/spring
  working_dir: /opt/spring/libs
  command: java -Xmx8m -Xss256k -jar hello-world-1.0-SNAPSHOT.jar
  mem_limit: 100m
  memswap_limit: 0
